services:
  web:
    build: .
    container_name: interactive_map_web
    ports:
      - "8081:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_ENGINE=postgres
      - DB_HOST=db
      - DB_NAME=lipetsk_institutions_db
      - DB_USER=user
      - DB_PASS=password
      - DB_PORT=5432
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    container_name: interactive_map_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lipetsk_institutions_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: interactive_map_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge