# Generated by Django 6.0.4 on 2026-05-03 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_copy_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")
    Administrator = apps.get_model("mapapp", "Administrator")
    PortalUser = apps.get_model("mapapp", "PortalUser")
    ActionLog = apps.get_model("mapapp", "ActionLog")

    admin_group, _ = Group.objects.get_or_create(name="administrators")
    portal_group, _ = Group.objects.get_or_create(name="portal_users")

    for admin in Administrator.objects.all():
        user = User.objects.filter(username=admin.login).first()
        if not user:
            kwargs = {
                "username": admin.login,
                "email": admin.email,
                "first_name": admin.full_name,
                "password": admin.password_hash,
                "is_staff": True,
            }
            if not User.objects.filter(pk=admin.id).exists():
                kwargs["id"] = admin.id
            user = User.objects.create(**kwargs)
        else:
            user.email = admin.email
            user.first_name = admin.full_name
            user.password = admin.password_hash
            user.is_staff = True
            user.save(update_fields=["email", "first_name", "password", "is_staff"])
        user.groups.add(admin_group)

    for portal in PortalUser.objects.all():
        user = User.objects.filter(username=portal.login).first()
        if not user:
            user = User.objects.create(
                username=portal.login,
                email=portal.email,
                first_name=portal.full_name,
                password=portal.password_hash,
            )
        else:
            user.email = portal.email
            user.first_name = portal.full_name
            user.password = portal.password_hash
            user.save(update_fields=["email", "first_name", "password"])
        user.groups.add(portal_group)

    # Если в ActionLog есть ссылки на удалённых администраторов,
    # создаём технических auth_user с нужным PK, чтобы FK миграция прошла.
    logged_admin_ids = set(ActionLog.objects.values_list("administrator_id", flat=True))
    for admin_id in logged_admin_ids:
        if not admin_id:
            continue
        if User.objects.filter(pk=admin_id).exists():
            continue
        legacy_admin = Administrator.objects.filter(pk=admin_id).first()
        if legacy_admin:
            username = legacy_admin.login
            email = legacy_admin.email
            first_name = legacy_admin.full_name
            password = legacy_admin.password_hash
        else:
            username = f"legacy_admin_{admin_id}"
            email = f"legacy_admin_{admin_id}@local"
            first_name = "Legacy administrator"
            password = "!"
        if User.objects.filter(username=username).exists():
            username = f"{username}_{admin_id}"
        user = User.objects.create(
            id=admin_id,
            username=username,
            email=email,
            first_name=first_name,
            password=password,
            is_staff=True,
        )
        user.groups.add(admin_group)


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_portal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(forwards_copy_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='actionlog',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PortalUser',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
