# Generated by Django 6.0.4 on 2026-05-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_repair_auth_user_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityCriterionType',
            fields=[
                ('code', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='accessibility_criteria',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='mapapp.accessibilitycriteriontype'),
        ),
    ]
