# Generated by Django 6.0.4 on 2026-05-05 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0006_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_notifications', to='mapapp.actionlog')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_notifications', to='mapapp.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'action_log'), name='uniq_profile_notification_per_user_action')],
            },
        ),
    ]
