from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.profile_page, name="profile_page"),
    path("district/<int:district_id>/", views.district_page, name="district_page"),
    path("institution/new/", views.institution_create_page, name="institution_create_page"),
    path("institution/<int:institution_id>/edit/", views.institution_edit_page, name="institution_edit_page"),
    path("admin/", views.index, name="admin_ui"),
    path("api/get_districts", views.get_districts),
    path("api/get_links", views.get_links),
    path("api/get_institutions", views.get_institutions),
    path("api/search_institutions", views.search_institutions),
    path("api/get_institution", views.get_institution),
    path("api/get_favorites", views.get_favorites),
    path("api/update_profile", views.update_profile),
    path("api/update_portal_main_info", views.update_portal_main_info),
    path("api/profile_match_institutions", views.profile_match_institutions),
    path("api/add_favorite", views.add_favorite),
    path("api/remove_favorite", views.remove_favorite),
    path("api/get_directors", views.get_directors),
    path("api/get_director", views.get_director),
    path("api/login", views.login),
    path("api/logout", views.logout),
    path("api/check_session", views.check_session),
    path("api/register", views.register),
    path("api/register_portal_user", views.register_portal_user),
    path("api/login_portal", views.login_portal_user),
    path("api/create_review", views.create_review),
    path("api/get_my_review", views.get_my_review),
    path("api/update_my_review", views.update_my_review),
    path("api/delete_my_review", views.delete_my_review),
    path("api/approve_review", views.approve_review),
    path("api/disapprove_review", views.disapprove_review),
    path("api/edit_review", views.edit_review_placeholder),
    path("api/get_admin_user_reviews", views.get_admin_user_reviews),
    path("api/get_admin_institution_reviews", views.get_admin_institution_reviews),
    path("api/delete_review", views.delete_review_by_admin),
    path("api/export_report", views.export_admin_report),
    path("api/create_institution", views.create_institution),
    path("api/delete_user", views.delete_user),
    path("api/set_user_block", views.set_user_block),
    path("api/update_institution", views.update_institution),
    path("api/delete_institution", views.delete_institution),
    # Legacy aliases for cached clients (can be removed later).
    path("api/get_districts.php", views.get_districts),
    path("api/get_links.php", views.get_links),
    path("api/get_institutions.php", views.get_institutions),
    path("api/search_institutions.php", views.search_institutions),
    path("api/get_institution.php", views.get_institution),
    path("api/get_favorites.php", views.get_favorites),
    path("api/update_profile.php", views.update_profile),
    path("api/update_portal_main_info.php", views.update_portal_main_info),
    path("api/profile_match_institutions.php", views.profile_match_institutions),
    path("api/add_favorite.php", views.add_favorite),
    path("api/remove_favorite.php", views.remove_favorite),
    path("api/get_directors.php", views.get_directors),
    path("api/get_director.php", views.get_director),
    path("api/login.php", views.login),
    path("api/logout.php", views.logout),
    path("api/check_session.php", views.check_session),
    path("api/register.php", views.register),
    path("api/register_portal_user.php", views.register_portal_user),
    path("api/login_portal.php", views.login_portal_user),
    path("api/create_review.php", views.create_review),
    path("api/get_my_review.php", views.get_my_review),
    path("api/update_my_review.php", views.update_my_review),
    path("api/delete_my_review.php", views.delete_my_review),
    path("api/approve_review.php", views.approve_review),
    path("api/disapprove_review.php", views.disapprove_review),
    path("api/edit_review.php", views.edit_review_placeholder),
    path("api/get_admin_user_reviews.php", views.get_admin_user_reviews),
    path("api/get_admin_institution_reviews.php", views.get_admin_institution_reviews),
    path("api/delete_review.php", views.delete_review_by_admin),
    path("api/export_report.php", views.export_admin_report),
    path("api/create_institution.php", views.create_institution),
    path("api/delete_user.php", views.delete_user),
    path("api/set_user_block.php", views.set_user_block),
    path("api/update_institution.php", views.update_institution),
    path("api/delete_institution.php", views.delete_institution),
]
